# Generated by Django 2.1.7 on 2019-04-16 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('blog', '0006_auto_20190409_1139'),
        ('blog', '0006_auto_20190409_1143'),
        ('blog', '0003_auto_20190326_1253'),
    ]

    operations = [
    ]
