# Generated by Django 2.1.7 on 2019-04-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_merge_20190416_1109'),
        # ('blog', '0006_auto_20190409_1139'),
    ]

    operations = [
    ]
