# Generated by Django 2.1.7 on 2019-04-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190414_2007'),
        ('shop', '0002_item_photo'),
    ]

    operations = [
    ]
