# Generated by Django 2.1.7 on 2019-04-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_merge_20190416_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
